#!/usr/bin/env python3
"""Genera splash_logo.c con la autocaravana recortada (fondo eliminado con
rembg/u2net) sobre fondo oscuro, en RGB565 sin alpha. 480x256 -> ~245 KB."""

import os
from PIL import Image
from rembg import remove

SRC = "/media/4TB/joint.jpg"
OUT_DIR = os.path.dirname(os.path.abspath(__file__))
TARGET_W = 720
TARGET_H = 400
BG_COLOR = (6, 8, 12)


def main():
    im_src = Image.open(SRC).convert("RGB")
    print(f"Original: {im_src.size}")
    # Quitar fondo con rembg (devuelve RGBA con alpha = sujeto)
    cut = remove(im_src)
    print(f"rembg:    {cut.size}, mode={cut.mode}")
    # Bounding-box del sujeto via canal alpha → recortar margenes
    alpha = cut.split()[-1]
    bbox = alpha.getbbox()
    if bbox is None:
        raise RuntimeError("rembg no encontro sujeto")
    cut = cut.crop(bbox)
    print(f"Cropped:  {cut.size}")
    # Resize manteniendo aspect ratio dentro de TARGET_W x TARGET_H
    cut.thumbnail((TARGET_W, TARGET_H), Image.LANCZOS)
    # Componer sobre fondo oscuro
    bg = Image.new("RGB", (TARGET_W, TARGET_H), BG_COLOR)
    ox = (TARGET_W - cut.size[0]) // 2
    oy = (TARGET_H - cut.size[1]) // 2
    bg.paste(cut, (ox, oy), cut)  # mascara = alpha del propio cut
    print(f"Final:    {bg.size}")
    bg.save(os.path.join(OUT_DIR, "splash_logo.png"))

    # RGB565 little-endian, sin alpha
    out = bytearray()
    px = bg.load()
    for y in range(bg.height):
        for x in range(bg.width):
            r, g, b = px[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            out.append(v & 0xFF)
            out.append((v >> 8) & 0xFF)

    c_path = os.path.join(OUT_DIR, "splash_logo.c")
    with open(c_path, "w") as f:
        f.write("/* Auto-generated by gen_splash.py — no editar a mano */\n")
        f.write("#include <lvgl.h>\n\n")
        f.write("static const uint8_t splash_logo_map[] = {\n")
        for i in range(0, len(out), 16):
            chunk = out[i:i + 16]
            f.write("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n\n")
        f.write("const lv_img_dsc_t splash_logo = {\n")
        f.write("  .header.always_zero = 0,\n")
        f.write("  .header.reserved    = 0,\n")
        f.write(f"  .header.w           = {bg.width},\n")
        f.write(f"  .header.h           = {bg.height},\n")
        f.write("  .header.cf          = LV_IMG_CF_TRUE_COLOR,\n")
        f.write(f"  .data_size          = {len(out)},\n")
        f.write("  .data               = splash_logo_map,\n")
        f.write("};\n")
    print(f"Escrito {c_path}  ({len(out)} bytes raw)")


if __name__ == "__main__":
    main()
