#!/usr/bin/env python3
"""Genera iconos PNG minimalistas tipo Venus OS y los convierte a archivos .c
con lv_img_dsc_t para LVGL (formato RGB565 + 8-bit alpha, little-endian)."""

import os
from PIL import Image, ImageDraw

SIZE = 64
OUT_DIR = os.path.dirname(os.path.abspath(__file__))


def rgb565_alpha_bytes(img: Image.Image) -> bytes:
    """RGBA -> bytes en formato LV_IMG_CF_TRUE_COLOR_ALPHA (3 bytes/pixel,
    little-endian, sin LV_COLOR_16_SWAP)."""
    out = bytearray()
    px = img.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = px[x, y]
            # RGB565
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            out.append(v & 0xFF)        # low byte
            out.append((v >> 8) & 0xFF) # high byte
            out.append(a)
    return bytes(out)


def write_lvgl_c(name: str, img: Image.Image) -> None:
    data = rgb565_alpha_bytes(img)
    c_path = os.path.join(OUT_DIR, f"icon_{name}.c")
    with open(c_path, "w") as f:
        f.write("/* Auto-generated by gen_icons.py — no editar a mano */\n")
        f.write("#include <lvgl.h>\n\n")
        f.write(f"static const uint8_t icon_{name}_map[] = {{\n")
        # 16 bytes por línea
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            f.write("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n\n")
        f.write(f"const lv_img_dsc_t icon_{name} = {{\n")
        f.write("  .header.always_zero = 0,\n")
        f.write("  .header.reserved    = 0,\n")
        f.write(f"  .header.w           = {img.width},\n")
        f.write(f"  .header.h           = {img.height},\n")
        f.write("  .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,\n")
        f.write(f"  .data_size          = {len(data)},\n")
        f.write(f"  .data               = icon_{name}_map,\n")
        f.write("};\n")
    png_path = os.path.join(OUT_DIR, f"icon_{name}.png")
    img.save(png_path)
    print(f"{name}: {len(data)} bytes  ->  {c_path}")


def make_canvas():
    return Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))


def draw_battery(color):
    """Batería de coche: vista frontal con dos postes (+/-) y etiqueta 12V."""
    img = make_canvas()
    d = ImageDraw.Draw(img)
    # Postes superiores
    d.rectangle((12, 10, 20, 18), fill=color)   # poste izquierdo (+)
    d.rectangle((44, 10, 52, 18), fill=color)   # poste derecho (-)
    # Signo + sobre el poste izquierdo
    d.line((13, 5, 19, 5), fill=color, width=2)
    d.line((16, 2, 16, 8), fill=color, width=2)
    # Signo - sobre el poste derecho
    d.line((45, 5, 51, 5), fill=color, width=2)
    # Cuerpo principal de la batería
    d.rounded_rectangle((4, 18, 60, 58), radius=5, outline=color, width=4)
    # Tapa superior (banda más oscura) — línea horizontal
    d.line((4, 28, 60, 28), fill=color, width=2)
    # Separadores de las 6 celdas en la tapa
    for x in (13, 22, 31, 40, 49):
        d.line((x, 18, x, 28), fill=color, width=2)
    # Etiqueta central simulando "12V" con dos rayas
    d.rounded_rectangle((16, 34, 48, 52), radius=2, outline=color, width=2)
    d.line((20, 39, 44, 39), fill=color, width=3)
    d.line((20, 47, 38, 47), fill=color, width=3)
    return img


def draw_solar(color):
    img = make_canvas()
    d = ImageDraw.Draw(img)
    # Sol arriba a la derecha
    cx, cy, r = 48, 16, 7
    d.ellipse((cx - r, cy - r, cx + r, cy + r), fill=color)
    for ang_x, ang_y in ((0, -1), (1, 0), (1, -1), (-1, -1), (-1, 0)):
        x1 = cx + ang_x * (r + 2)
        y1 = cy + ang_y * (r + 2)
        x2 = cx + ang_x * (r + 7)
        y2 = cy + ang_y * (r + 7)
        d.line((x1, y1, x2, y2), fill=color, width=3)
    # Panel solar inclinado: trapecio
    d.polygon([(8, 56), (54, 56), (44, 26), (16, 26)], outline=color, width=4)
    # Líneas verticales de celdas
    for x in (24, 33, 42):
        d.line((x, 28, x - 6, 54), fill=color, width=2)
    # Líneas horizontales
    d.line((14, 36, 50, 36), fill=color, width=2)
    d.line((11, 46, 53, 46), fill=color, width=2)
    return img


def draw_dcdc(color):
    img = make_canvas()
    d = ImageDraw.Draw(img)
    # Dos rectángulos (in/out) conectados con flecha
    d.rounded_rectangle((4, 18, 26, 46), radius=4, outline=color, width=4)
    d.rounded_rectangle((38, 18, 60, 46), radius=4, outline=color, width=4)
    # Flecha del primero al segundo
    d.line((28, 32, 36, 32), fill=color, width=4)
    d.polygon([(36, 28), (40, 32), (36, 36)], fill=color)
    # "DC" pequeñito en cada caja
    # Onda en el primero (rectificada / continua)
    d.line((9, 32, 13, 32), fill=color, width=3)
    d.line((13, 32, 13, 28), fill=color, width=3)
    d.line((13, 32, 17, 32), fill=color, width=3)
    d.line((17, 32, 17, 36), fill=color, width=3)
    d.line((17, 32, 21, 32), fill=color, width=3)
    # Línea continua en el segundo
    d.line((43, 32, 55, 32), fill=color, width=3)
    d.line((43, 28, 43, 36), fill=color, width=2)
    d.line((55, 28, 55, 36), fill=color, width=2)
    return img


def draw_home(color):
    img = make_canvas()
    d = ImageDraw.Draw(img)
    # Tejado (triángulo)
    d.polygon([(8, 32), (32, 8), (56, 32)], outline=color, width=4)
    # Cuerpo
    d.rectangle((14, 32, 50, 56), outline=color, width=4)
    # Puerta
    d.rectangle((26, 40, 38, 56), fill=color)
    # Chimenea (pequeño rectángulo en el tejado derecho)
    d.rectangle((42, 14, 48, 24), fill=color)
    return img


COLORS = {
    "battery": (255, 152, 0, 255),  # naranja
    "solar":   (0, 200, 81, 255),   # verde
    "dcdc":    (79, 195, 247, 255), # cyan
    "home":    (79, 195, 247, 255), # cyan
}

DRAWERS = {
    "battery": draw_battery,
    "solar":   draw_solar,
    "dcdc":    draw_dcdc,
    "home":    draw_home,
}


def main():
    for name, drawer in DRAWERS.items():
        img = drawer(COLORS[name])
        write_lvgl_c(name, img)


if __name__ == "__main__":
    main()
