#!/usr/bin/env python3
"""Convierte fan_blades.png a icon_fan.c (lv_img_dsc_t LV_IMG_CF_TRUE_COLOR_ALPHA).

El PNG fuente es 256x256 RGBA, blanco sobre transparente. Lo redimensiono
a 80x80 para que tenga buena definicion incluso girado, y mantengo el
formato RGBA para recoloring dinamico (gris/cyan segun fan_percent)."""

import os
from PIL import Image

SIZE = 80
HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, "fan_blades.png")
OUT_C = os.path.join(HERE, "icon_fan.c")
OUT_PNG = os.path.join(HERE, "icon_fan.png")


def rgb565_alpha_bytes(img: Image.Image) -> bytes:
    out = bytearray()
    px = img.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = px[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            out.append(v & 0xFF)
            out.append((v >> 8) & 0xFF)
            out.append(a)
    return bytes(out)


from PIL import ImageDraw

img = Image.open(SRC).convert("RGBA").resize((SIZE, SIZE), Image.LANCZOS)

# Aplicar mascara circular: quedarse solo con las aspas (descartar el
# marco cuadrado con las esquinas y los tornillos). El circulo de las
# aspas esta inscrito en el cuadrado con algo de margen interior.
mask = Image.new("L", (SIZE, SIZE), 0)
draw = ImageDraw.Draw(mask)
inset = SIZE // 12   # ~6 px en 80x80 — margen para "comer" el marco
draw.ellipse((inset, inset, SIZE - inset, SIZE - inset), fill=255)

# Combinar la alpha original con la mascara (AND): pixel transparente
# si esta fuera del circulo.
r, g, b, a = img.split()
a = Image.eval(a, lambda v: v).point(lambda v: v)  # copia
import PIL.ImageChops as Chops
a = Chops.multiply(a, mask)
img = Image.merge("RGBA", (r, g, b, a))

img.save(OUT_PNG, "PNG")
data = rgb565_alpha_bytes(img)

with open(OUT_C, "w") as f:
    f.write("/* Auto-generated by gen_fan_icon.py — no editar a mano */\n")
    f.write("#include <lvgl.h>\n\n")
    f.write("static const uint8_t icon_fan_map[] = {\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        f.write("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
    f.write("};\n\n")
    f.write("const lv_img_dsc_t icon_fan = {\n")
    f.write("  .header.always_zero = 0,\n")
    f.write("  .header.reserved    = 0,\n")
    f.write(f"  .header.w           = {SIZE},\n")
    f.write(f"  .header.h           = {SIZE},\n")
    f.write("  .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,\n")
    f.write(f"  .data_size          = {len(data)},\n")
    f.write("  .data               = icon_fan_map,\n")
    f.write("};\n")

print(f"icon_fan: {SIZE}x{SIZE}, {len(data)} bytes -> {OUT_C}")
